name: Check TOC References

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-toc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get list of changed files
      id: changed-files
      run: |
        changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
        echo "::set-output name=files::$changed_files"

    - name: Check TOC references
      run: |
        missing_files=()
        for file in ${{ steps.changed-files.outputs.files }}; do
          if [[ $file == *.md ]]; then
            folder=$(dirname "$file")
            toc_file="$folder/toc.yml"
            if [ -f "$toc_file" ]; then
              if ! grep -q "href: $file" "$toc_file"; then
                missing_files+=("$file")
              fi
            else
              echo "TOC file not found in $folder"
              exit 1
            fi
          fi
        done

        if [ ${#missing_files[@]} -ne 0 ]; then
          echo "The following markdown files are missing in their respective toc.yml:"
          for file in "${missing_files[@]}"; do
            echo "$file"
          done
          exit 1
        fi
