name: PR Assigner

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            // Add all usernames you want as assignees to this array
            const assignees = [
              'joudot',
              'another-username',
              'third-username',
              'fourth-username'
            ];
            
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: assignees
            });